# Generated by Django 5.2.3 on 2025-09-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gestion_date', models.DateTimeField(auto_now_add=True)),
                ('Gestion_quantite', models.PositiveIntegerField()),
                ('ProduitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
                ('ResponsableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable.responsable')),
            ],
        ),
    ]
