# Generated by Django 5.2.3 on 2025-09-18 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit_nom', models.CharField(max_length=40)),
                ('Produit_description', models.TextField(blank=True, null=True)),
                ('Produit_reference', models.TextField(blank=True, null=True)),
                ('Produit_prix', models.IntegerField()),
                ('Produit_photo', models.ImageField(blank=True, null=True, upload_to='produits/photos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Produit_quantite', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Produit_categorie', models.CharField(choices=[('Electromenager', 'Électroménager'), ('MaisonCuisine', 'Maison & Cuisine'), ('MobilierLiterie', 'Mobilier & Literie'), ('Electronique', 'Électronique & Multimédia'), ('Mode', 'Mode & Accessoires'), ('Transport', 'Véhicules & Transport'), ('Energie', 'Énergie & Solaire')], default='MaisonCuisine', max_length=30)),
            ],
        ),
    ]
