# Generated by Django 5.2.3 on 2025-10-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Produit_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
