# Generated by Django 5.2.3 on 2025-10-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_produit_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Produit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/photos/'),
        ),
    ]
