# Generated by Django 5.2.3 on 2025-10-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_alter_produit_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Produit_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
