# Generated by Django 5.2.3 on 2025-10-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0010_alter_produit_produit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Produit_photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
