# Generated by Django 5.2.3 on 2025-10-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0011_produit_produit_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='Produit_photo_url',
        ),
    ]
