# Generated by Django 5.2.3 on 2025-10-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0013_produit_produit_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='Produit_photo_url',
        ),
        migrations.AlterField(
            model_name='produit',
            name='Produit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/photos/'),
        ),
    ]
