# Generated by Django 5.2.3 on 2025-11-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0014_remove_produit_produit_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Produit_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
