# Generated by Django 5.2.3 on 2025-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_email', models.EmailField(max_length=254, null=True)),
                ('Client_nom', models.CharField(max_length=100, null=True)),
                ('Client_prenom', models.CharField(max_length=100, null=True)),
                ('Client_cin', models.CharField(max_length=12, null=True, unique=True)),
                ('Client_photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('Client_adresse', models.TextField(null=True)),
                ('Client_quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('Client_telephone', models.CharField(max_length=20, null=True)),
                ('Client_telephone1', models.CharField(max_length=20, null=True)),
                ('Client_telephone2', models.CharField(max_length=20, null=True)),
                ('Client_telephone3', models.CharField(max_length=20, null=True)),
                ('Client_telephone4', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('Client_role', models.CharField(default='client', max_length=20)),
            ],
        ),
    ]
