services:
  backend:
    build: .
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app # Monte tout le projet pour le hot-reload
    command: python manage.py runserver 0.0.0.0:8000
