# Generated by Django 5.2.3 on 2025-09-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('produit', '0001_initial'),
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achat_quantite', models.PositiveIntegerField()),
                ('Achat_montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Achat_date', models.DateTimeField(auto_now_add=True)),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('ProduitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
                ('ResponsableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='achats.achat')),
            ],
        ),
    ]
