# Generated by Django 5.2.3 on 2025-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vue_client',
            field=models.BooleanField(default=False),
        ),
    ]
