# Generated by Django 5.2.3 on 2025-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_notification_vue_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mode_reception',
            field=models.CharField(choices=[('magasin', 'Récupération au magasin'), ('livraison', 'Livraison à domicile')], default='magasin', max_length=20),
        ),
    ]
