# Generated by Django 5.2.3 on 2025-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_notification_mode_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
