# Generated by Django 5.2.3 on 2025-10-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_notification_quantite'),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='quantite',
        ),
        migrations.CreateModel(
            name='NotificationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='achats.notification')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
    ]
