"""
Django settings for monbackend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# import pymysql
# pymysql.install_as_MySQLdb()
SITE_URL = "http://127.0.0.1:8000"
MVOLA_SANDBOX_TOKEN = "eyJ4NXQiOiJaREUzWW1RNFkyRmtZekprTmpNMk5EVmtZVE5oTkRSak16azFObVEyWXprelkyUTFaVFZqWVEiLCJraWQiOiJNVGRsTXpneFpqZGtNakk0WmpKbVlUZ3dNRFJpWWpNMU1tUmhOamxoTUdNME1XTmtPV05tT1RobU16VXlNMlUxTkRZNE5UWXhOMk01TW1SbU5XUTRPQV9SUzI1NiIsInR5cCI6ImF0K2p3dCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjaHJpc3RpbmVyYXNvYW5hbWJpbmluYUBnbWFpbC5jb20iLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6Ik9LOVVrMjZlMmtRaGNSeDFhNllLN2FiWmJ4Y2EiLCJuYmYiOjE3NjIyNDA4ODAsImF6cCI6Ik9LOVVrMjZlMmtRaGNSeDFhNllLN2FiWmJ4Y2EiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvZGV2ZWxvcGVyLm12b2xhLm1nXC9vYXV0aDJcL3Rva2VuIiwicmVhbG0iOnsic2lnbmluZ190ZW5hbnQiOiJjYXJib24uc3VwZXIifSwiZXhwIjoxNzYyMjQ0NDgwLCJpYXQiOjE3NjIyNDA4ODAsImp0aSI6IjgzZjA1Y2VlLTBmMmQtNGYzNi05N2M5LTc1NWYxYzBmOTg3NyJ9.MQsezGQCiYGRW4H8AwlWX5SjpjeTJa5-1j8uo0outAIQkZvESIGfsBzoFJgUIFjMjaspH3FaRIQ_kjX5TmjH9bOAnu2tBaeMzPP3YdkgJIwUu5KCeRMnUFFl5O8ytjB6Wu6gc1KF11Y2oVip23DXL6jP4wgvSW4a4pO5nM8094i2Ze-m13dzp7U3Sq_e0LFoGL7wK3PqEuxAyonzFOhGnE_9emQtkWtWOnuP0NUkBNhAo8A0-xbGr6bQc7ccZv25lyZPloB4cPEHTIOzJ4EhTB4GIW27CzvFbH5Fd3280m5q9M-oUkdOx3jQ4zcdSzcdwhc6nsIONe8xOYo4zdwbvw"
MVOLA_CONSUMER_KEY = "OK9Uk26e2kQhcRx1a6YK7abZbxca"
MVOLA_CONSUMER_SECRET = "GvhXrTyorPrwrKHRm8lHmCedFhUa"

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

import paypalrestsdk

paypalrestsdk.configure({
  "mode": "live", # Test
  "client_id": "ASUfOszWNTev5zOMiZVfl2AolG9_kN0Z9K8pB2qdyZ2SsIFcBONRrQsKT8mOwgWH42w88z4xFihKY-P4",
  "client_secret": "EC9Xh-7BA-nmpu1C0zGVH7I-0nI-7gOJEPkMl_2KVyH4NXznkKa8VFFg0BfpVdxiT1KF6UsWdpolXnst"
})

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-gybr)@9q7a&l&k$d6%xtwu51v3m5q%95hja(#%v2yno^t2d5=a'

# SECURITY WARNING: don't run with debug turned on in production!




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework',
    'corsheaders',
    'responsable',
    'client',
    'produit',
    'gestion',
    'paiement',
    'achats',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'monbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monbackend.wsgi.application'
DB_LIVE = os.getenv("DB_LIVE")
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',          # JSON pour les appels API
        'rest_framework.renderers.BrowsableAPIRenderer',  # Formulaire simple dans le navigateur
    )
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# if DB_LIVE in ["False", False]:
#     DATABASES = {
#         'default': {
            # 'ENGINE': 'django.db.backends.postgresql',
            # 'NAME': 'test',
            # 'USER': 'postgres',
            # 'PASSWORD': '1234',
            # 'HOST': 'localhost',
            # 'PORT': '5432',
#         }
#     }

# else :

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': os.getenv("DB_NAME"),
#             'USER': os.getenv("DB_USER"),
#             'PASSWORD': os.getenv("DB_PASSWORD"),
#             'HOST': os.getenv("DB_HOST"), 
#             'PORT': os.getenv("DB_PORT"),        
#         }
#     }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'aufsarl1_produit',
#         'USER': 'aufsarl1_benesrf',
#         'PASSWORD': 'BenesRf@2025',
#         'HOST': 'hala.gasyweb.com', 
#         'PORT': '3306',        
#     }
# }

# DATABASES = {
#     'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'auf-sarl',
#             'USER': 'postgres',
#             'PASSWORD': '1234',
#             'HOST': 'localhost',
#             'PORT': '5432',
#     }
# }
import dj_database_url

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-gybr)@9q7a&l&k$d6%xtwu51v3m5q%95hja(#%v2yno^t2d5=a'  # clé locale par défaut
)

# Mode production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Configuration PostgreSQL depuis Render
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get(
            'DATABASE_URL',
            'postgresql://postgre:5kr7i1RC8OFbbsX3fzqptTAE3gP91USM@dpg-d3o83ud6ubrc73a85cj0-a.oregon-postgres.render.com/aufsarl'
        ),
        conn_max_age=600,
        ssl_require=True
    )
}
DEBUG = True
  # ⚠️ Mettre True uniquement en dev, False en prod



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tinyroane@gmail.com'          # Remplace par ton email Gmail
EMAIL_HOST_PASSWORD = 'vtpu jouc llfs nhau'                # Mot de passe d'application Gmail, pas ton mot de passe normal
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://venteproduit.auf-sarlu.mg",
    "https://vente.auf-sarlu.mg",# frontend
    "https://myvente.auf-sarlu.mg",
    "https://myapp.auf-sarlu.mg",# frontend
    "http://localhost:3000",       # dev local si besoin
]

# ----- HOSTS -----
ALLOWED_HOSTS = [
    "api.auf-sarlu.mg",
    "app.auf-sarlu.mg",
    "venteproduit.auf-sarlu.mg",
    "lu.auf-sarlu.mg",
    "vente.auf-sarlu.mg",
    "myapp.auf-sarlu.mg",
    "myvente.auf-sarlu.mg",
    "localhost",
    "projetfin.onrender.com"
]
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

