# Generated by Django 5.2.3 on 2025-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsable_email', models.EmailField(max_length=254, unique=True)),
                ('Responsable_nom', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Responsable_prenom', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Responsable_adresse', models.TextField(blank=True, default=None, null=True)),
                ('Responsable_telephone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Responsable_role', models.CharField(choices=[('admin', 'Admin'), ('vendeur', 'Vendeur')], default='vendeur', max_length=20)),
                ('Responsable_photo', models.ImageField(blank=True, null=True, upload_to='responsables/photos/')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
