# Generated by Django 5.2.3 on 2025-09-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paiement_montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paiement_montantchoisi', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('Paiement_mode', models.CharField(choices=[('cash', 'Cash'), ('carte', 'Carte')], max_length=50)),
                ('Paiement_type', models.CharField(choices=[('mensuel', 'Mensuel'), ('comptant', 'Comptant')], max_length=50)),
                ('Paiement_date', models.DateTimeField(auto_now_add=True)),
                ('Paiement_datechoisi', models.DateField(blank=True, default=None, null=True)),
                ('AchatsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_details', to='achats.achat')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiement.paiement')),
            ],
        ),
    ]
