# Generated by Django 5.2.3 on 2025-10-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_entreprise', models.CharField(default='0334990938', help_text='Numéro mobile de l’entreprise (Airtel Money, Mvola, etc.)', max_length=20)),
                ('mode', models.CharField(choices=[('airtel', 'Airtel Money'), ('mvola', 'MVola'), ('orange', 'Orange Money')], default='airtel', max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
