# Generated by Django 5.2.3 on 2025-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_paiementmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmobile',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paiementmobile',
            name='mode',
            field=models.CharField(choices=[('airtel', 'Airtel Money'), ('mvola', 'MVola'), ('orange', 'Orange Money')], default='mvola', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiementmobile',
            name='numero_entreprise',
            field=models.CharField(default='0340000001', max_length=20),
        ),
    ]
