# Generated by Django 5.2.3 on 2025-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_paiementmobile_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_entreprise',
            field=models.CharField(blank=True, default='0340000001', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='Paiement_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('carte', 'Carte'), ('airtel', 'Airtel Money'), ('mvola', 'MVola'), ('orange', 'Orange Money')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='Paiement_montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='Paiement_type',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('comptant', 'Comptant')], max_length=50, null=True),
        ),
    ]
